#!/sbin/runscript
# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

SVCSUFFIX=${SVCNAME#*.}

depend() {
	need net
	use rabbitmq logger dns
}

DEFAULT_PID_FILE="/var/run/celery/celeryev.pid"
DEFAULT_LOG_FILE="/var/log/celery/celeryev.log"
DEFAULT_LOG_LEVEL="INFO"
DEFAULT_CELERYEV="/usr/bin/celeryev"

CELERYEV=${CELERYEV:-$DEFAULT_CELERYEV}
CELERYEV_PID_FILE=${CELERYEV_PID_FILE:-${CELERYEV_PIDFILE:-$DEFAULT_PID_FILE}}
CELERYEV_LOG_FILE=${CELERYEV_LOG_FILE:-${CELERYEV_LOGFILE:-$DEFAULT_LOG_FILE}}
CELERYEV_LOG_LEVEL=${CELERYEV_LOG_LEVEL:-${CELERYEV_LOG_LEVEL:-$DEFAULT_LOG_LEVEL}}

export CELERY_LOADER

if [ -z "$CELERYEV_CAM" ]; then
	eerror "Missing CELERYEV_CAM variable"
	exit
fi

CELERYEV_OPTS="$CELERYEV_OPTS -f $CELERYEV_LOG_FILE -l $CELERYEV_LOG_LEVEL -c $CELERYEV_CAM"

CELERYEV_LOG_DIR=`dirname $CELERYEV_LOG_FILE`
CELERYEV_PID_DIR=`dirname $CELERYEV_PID_FILE`
if [ ! -d "$CELERYEV_LOG_DIR" ]; then
	mkdir -p $CELERYEV_LOG_DIR
fi
if [ ! -d "$CELERYEV_PID_DIR" ]; then
	mkdir -p $CELERYEV_PID_DIR
fi

# Extra start-stop-daemon options, like user/group.
if [ -n "$CELERYEV_USER" ]; then
	DAEMON_OPTS="$DAEMON_OPTS --uid $CELERYEV_USER"
	chown "$CELERYEV_USER" $CELERYBEAT_LOG_DIR $CELERYEV_PID_DIR
fi
if [ -n "$CELERYEV_GROUP" ]; then
	DAEMON_OPTS="$DAEMON_OPTS --gid $CELERYEV_GROUP"
	chown "$CELERYEV_GROUP" $CELERYBEAT_LOG_DIR $CELERYEV_PID_DIR
fi

CELERYEV_CHDIR=${CELERYEV_CHDIR:-$CELERYD_CHDIR}
if [ -n "$CELERYEV_CHDIR" ]; then
	DAEMON_OPTS="$DAEMON_OPTS --workdir $CELERYEV_CHDIR"
fi


export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

check_dev_null() {
	if [ ! -c /dev/null ]; then
		eerror "/dev/null is not a character device!"
		return 1
	fi
	return 0
}

wait_pid () {
	pid=$1
	i=0
	while true; do
		kill -0 $pid 1>/dev/null 2>&1
		if [ $? -eq 1 ]; then
			return 0
		else
			kill -TERM "$pid"
			i=$((i + 1))
			if [ $i -gt 60 ]; then
				return 1
			else
				sleep 0.5
			fi
		fi
	done
}


start() {
	check_dev_null || return 1

	ebegin "Starting ${SVCNAME}"
	$CELERYEV $CELERYEV_OPTS $DAEMON_OPTS --detach \
		--pidfile="$CELERYEV_PID_FILE"
	eend $?
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	if [ -f "$CELERYEV_PID_FILE" ]; then
		wait_pid $(cat "$CELERYEV_PID_FILE")
	else
		eerror "not running"
	fi
	eend $?
}
